{% set name = "catann2" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:  

  ### knn_query_new version
  git_url: https://github.com/arita37/cat_catannlib.git
  # git_rev: c83fd9250d7eba67d487b540cbb7881bec0fb250   ### version 1
  git_rev: 389629c8abae8308335bf42664ecbc726c743aff     ### Version 3 new-query3
  
  ###Original : ok running
  #git_url: https://github.com/arita37/cat_catannlib.git
  # git_rev: e54e865b246fb97a9a1b865308124e0b547a102c

  
  
#source:
#  git_url: https://github.com/heal-research/operon
#  git_rev: 43dcc09c71c7ba1251284cb3eb59a54c17ec4319

build:
  number: 0
  script: |
    cd python_bindings
    # pip install -r requirements.txt
    # python setup.py install
    python -m pip install . -vv    
    
requirements:
  build:
    - make
    #- pip
    - cmake
    - python={{ python }}
    - gxx={{ gxx }}
    - numpy==1.19.2
    #- numpy<1.17.0
    #- blas
    #- pytest-runner
    #- libgomp
    - pybind11>=2.0

  run:
    - python={{ python }}
    - libstdcxx-ng
    #- numpy>=1.19.5
    - numpy==1.19.2

test:
  imports:
    - catannlib
  #source_files:
  #  - python_bindings/tests/

about:
  home: catann2
  license: Apache License 2.0
  license_family: APACHE
  summary: 'catann2'

extra:
  recipe-maintainers:
    - arita37
